import React from 'react'
import { Document, Page, Text, View } from '@react-pdf/renderer'
import { styles, colors } from './styles'

interface CompetitorDuelReportProps {
  siteA: string
  siteB: string
  date: string
  scores: { seo: { siteA: number; siteB: number }; aeo: { siteA: number; siteB: number }; geo: { siteA: number; siteB: number } }
  verdict?: string
  recommendations?: any[]
  backlinkA?: any
  backlinkB?: any
  linkGap?: any[]
}

function ScoreRow({ label, a, b, color }: { label: string; a: number; b: number; color: string }) {
  const winner = a > b ? 'A' : b > a ? 'B' : 'tie'
  return (
    <View style={[styles.row, { marginBottom: 8, gap: 8 }]}>
      <Text style={[styles.body, { width: 40, fontWeight: 'bold', color }]}>{label}</Text>
      <Text style={[styles.h3, { width: 40, textAlign: 'center', color: winner === 'A' ? colors.seo : colors.muted }]}>{a}</Text>
      <Text style={[styles.small, { width: 20, textAlign: 'center' }]}>vs</Text>
      <Text style={[styles.h3, { width: 40, textAlign: 'center', color: winner === 'B' ? colors.geo : colors.muted }]}>{b}</Text>
    </View>
  )
}

export function CompetitorDuelReport({ siteA, siteB, date, scores, verdict, recommendations, backlinkA, backlinkB, linkGap }: CompetitorDuelReportProps) {
  return (
    <Document>
      <Page size="A4" style={styles.coverPage}>
        <Text style={{ fontSize: 36, fontWeight: 'bold', color: colors.seo, marginBottom: 8 }}>Competitor Duel Report</Text>
        <Text style={{ fontSize: 12, color: colors.seo, marginBottom: 2 }}>{siteA}</Text>
        <Text style={{ fontSize: 10, color: colors.muted, marginBottom: 2 }}>vs</Text>
        <Text style={{ fontSize: 12, color: colors.geo, marginBottom: 24 }}>{siteB}</Text>
        <View style={[styles.card, { width: 300 }]}>
          <ScoreRow label="SEO" a={scores.seo.siteA} b={scores.seo.siteB} color={colors.seo} />
          <ScoreRow label="AEO" a={scores.aeo.siteA} b={scores.aeo.siteB} color={colors.aeo} />
          <ScoreRow label="GEO" a={scores.geo.siteA} b={scores.geo.siteB} color={colors.geo} />
        </View>
        {verdict && (
          <View style={[styles.card, { maxWidth: 400, marginTop: 12 }]}>
            <Text style={[styles.h4, { color: colors.seo, marginBottom: 4 }]}>Expert Verdict</Text>
            <Text style={styles.bodyLarge}>{verdict}</Text>
          </View>
        )}
        <Text style={{ fontSize: 8, color: colors.muted, position: 'absolute', bottom: 30 }}>Generated by Duelly.ai · {date}</Text>
      </Page>

      {/* Backlinks */}
      {backlinkA && backlinkB && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Backlink Comparison</Text>
          <View style={styles.divider} />
          <View style={[styles.row, { gap: 16 }]}>
            <View style={{ flex: 1 }}>
              <Text style={[styles.h4, { color: colors.seo }]}>{siteA}</Text>
              <Text style={styles.body}>DA: {backlinkA.metrics.domainAuthority} · Links: {backlinkA.metrics.totalBacklinks.toLocaleString()} · Domains: {backlinkA.metrics.linkingDomains.toLocaleString()}</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={[styles.h4, { color: colors.geo }]}>{siteB}</Text>
              <Text style={styles.body}>DA: {backlinkB.metrics.domainAuthority} · Links: {backlinkB.metrics.totalBacklinks.toLocaleString()} · Domains: {backlinkB.metrics.linkingDomains.toLocaleString()}</Text>
            </View>
          </View>
          {linkGap && linkGap.length > 0 && (
            <View style={{ marginTop: 16 }}>
              <Text style={[styles.h4, { color: colors.purple }]}>Link Gap ({linkGap.length} opportunities)</Text>
              {linkGap.slice(0, 10).map((g: any, i: number) => (
                <View key={i} style={[styles.row, { gap: 8, paddingVertical: 2 }]}>
                  <Text style={[styles.small, { width: 20, fontWeight: 'bold' }]}>{g.da}</Text>
                  <Text style={styles.small}>{g.domain}</Text>
                </View>
              ))}
            </View>
          )}
          <View style={styles.footer}><Text>Duelly.ai</Text><Text>{date}</Text></View>
        </Page>
      )}

      {/* Counter-Strategies */}
      {recommendations && recommendations.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Counter-Strategies</Text>
          <View style={styles.divider} />
          {recommendations.map((rec: any, i: number) => {
            const priority = (rec.roi || rec.priority || 'MEDIUM').toUpperCase()
            const priorityColor = priority === 'CRITICAL' ? colors.red : priority === 'HIGH' ? colors.yellow : colors.purple
            return (
              <View key={i} style={styles.card} wrap={false}>
                <View style={[styles.row, { gap: 4, marginBottom: 4 }]}>
                  <Text style={[styles.badge, { backgroundColor: `${priorityColor}20`, color: priorityColor }]}>{priority}</Text>
                </View>
                <Text style={[styles.h3, { marginBottom: 4 }]}>{i + 1}. {rec.title}</Text>
                {rec.description && <View style={styles.whyBox}><Text style={[styles.h4, { marginBottom: 2 }]}>Why This Matters</Text><Text style={styles.body}>{rec.description}</Text></View>}
                {rec.howToFix && <View style={styles.fixBox}><Text style={[styles.h4, { color: colors.seo, marginBottom: 2 }]}>How To Fix</Text><Text style={styles.body}>{rec.howToFix}</Text></View>}
                {rec.codeSnippet && <Text style={styles.codeBlock}>{rec.codeSnippet}</Text>}
              </View>
            )
          })}
          <View style={styles.footer}><Text>Duelly.ai</Text><Text>{date}</Text></View>
        </Page>
      )}
    </Document>
  )
}
