import React from 'react'
import { Document, Page, Text, View } from '@react-pdf/renderer'
import { styles, colors } from './styles'

interface KeywordArenaReportProps {
  keyword: string
  date: string
  userSiteUrl?: string
  userRank?: number | null
  totalSites: number
  sites: Array<{ url: string; title: string; scores: { seo: number | null; aeo: number | null; geo: number | null; overall: number | null }; googleRank: number | null; isUserSite: boolean }>
}

export function KeywordArenaReport({ keyword, date, userSiteUrl, userRank, totalSites, sites }: KeywordArenaReportProps) {
  const scored = sites.filter(s => s.scores.overall !== null)
  const seoLeader = scored.length > 0 ? scored.reduce((b, s) => (s.scores.seo ?? 0) > (b.scores.seo ?? 0) ? s : b, scored[0]) : null
  const aeoLeader = scored.length > 0 ? scored.reduce((b, s) => (s.scores.aeo ?? 0) > (b.scores.aeo ?? 0) ? s : b, scored[0]) : null
  const geoLeader = scored.length > 0 ? scored.reduce((b, s) => (s.scores.geo ?? 0) > (b.scores.geo ?? 0) ? s : b, scored[0]) : null

  return (
    <Document>
      <Page size="A4" style={styles.coverPage}>
        <Text style={{ fontSize: 36, fontWeight: 'bold', color: colors.seo, marginBottom: 8 }}>Keyword Arena Report</Text>
        <Text style={{ fontSize: 16, color: colors.text, marginBottom: 4 }}>"{keyword}"</Text>
        <Text style={{ fontSize: 10, color: colors.muted, marginBottom: 24 }}>{totalSites} sites analyzed · {date}</Text>
        {userRank && (
          <View style={[styles.card, { width: 300, marginBottom: 16 }]}>
            <Text style={[styles.h4, { color: colors.seo, marginBottom: 4 }]}>Your Position</Text>
            <Text style={styles.bodyLarge}>AI Rank: #{userRank} out of {scored.length} scored sites</Text>
          </View>
        )}

        {/* Leaders */}
        <View style={[styles.row, { gap: 12, marginBottom: 16 }]}>
          {[
            { label: 'SEO Leader', site: seoLeader, score: seoLeader?.scores.seo, color: colors.seo },
            { label: 'AEO Leader', site: aeoLeader, score: aeoLeader?.scores.aeo, color: colors.aeo },
            { label: 'GEO Leader', site: geoLeader, score: geoLeader?.scores.geo, color: colors.geo },
          ].map((l, i) => l.site && (
            <View key={i} style={[styles.card, { flex: 1, alignItems: 'center' }]}>
              <Text style={[styles.small, { marginBottom: 4 }]}>{l.label}</Text>
              <Text style={{ fontSize: 24, fontWeight: 'bold', color: l.color }}>{l.score ?? '—'}</Text>
              <Text style={[styles.small, { marginTop: 2 }]}>{(l.site.title || l.site.url).slice(0, 30)}</Text>
            </View>
          ))}
        </View>
        <Text style={{ fontSize: 8, color: colors.muted, position: 'absolute', bottom: 30 }}>Generated by Duelly.ai · {date}</Text>
      </Page>

      {/* Leaderboard */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.h2}>Leaderboard</Text>
        <View style={styles.divider} />
        <View style={[styles.row, { gap: 4, paddingBottom: 6, borderBottom: `1 solid ${colors.border}` }]}>
          <Text style={[styles.small, { width: 25, fontWeight: 'bold' }]}>#</Text>
          <Text style={[styles.small, { flex: 1, fontWeight: 'bold' }]}>Site</Text>
          <Text style={[styles.small, { width: 35, textAlign: 'center', fontWeight: 'bold' }]}>Google</Text>
          <Text style={[styles.small, { width: 30, textAlign: 'center', fontWeight: 'bold', color: colors.seo }]}>SEO</Text>
          <Text style={[styles.small, { width: 30, textAlign: 'center', fontWeight: 'bold', color: colors.aeo }]}>AEO</Text>
          <Text style={[styles.small, { width: 30, textAlign: 'center', fontWeight: 'bold', color: colors.geo }]}>GEO</Text>
          <Text style={[styles.small, { width: 35, textAlign: 'center', fontWeight: 'bold' }]}>Overall</Text>
        </View>
        {sites.map((site, i) => {
          const s = site.scores.overall !== null
          const rank = s ? sites.slice(0, i).filter(x => x.scores.overall !== null).length + 1 : '—'
          return (
            <View key={i} style={[styles.row, { gap: 4, paddingVertical: 4, borderBottom: `1 solid ${colors.border}`, backgroundColor: site.isUserSite ? `${colors.seo}10` : 'transparent' }]}>
              <Text style={[styles.small, { width: 25 }]}>{rank}</Text>
              <Text style={[styles.small, { flex: 1, color: site.isUserSite ? colors.seo : colors.text }]}>{(site.title || site.url).slice(0, 40)}{site.isUserSite ? ' ⭐' : ''}</Text>
              <Text style={[styles.small, { width: 35, textAlign: 'center' }]}>{site.googleRank ? `#${site.googleRank}` : '—'}</Text>
              <Text style={[styles.small, { width: 30, textAlign: 'center' }]}>{site.scores.seo ?? '—'}</Text>
              <Text style={[styles.small, { width: 30, textAlign: 'center' }]}>{site.scores.aeo ?? '—'}</Text>
              <Text style={[styles.small, { width: 30, textAlign: 'center' }]}>{site.scores.geo ?? '—'}</Text>
              <Text style={[styles.small, { width: 35, textAlign: 'center', fontWeight: 'bold' }]}>{site.scores.overall ?? '—'}</Text>
            </View>
          )
        })}
        <View style={styles.footer}><Text>Duelly.ai</Text><Text>{date}</Text></View>
      </Page>
    </Document>
  )
}
