import React from 'react'
import { Document, Page, Text, View } from '@react-pdf/renderer'
import { styles, colors } from './styles'

interface ProAuditReportProps {
  url: string
  date: string
  scores: { seo: number; aeo: number; geo: number }
  siteType?: string
  platform?: string
  overallFeedback?: string
  recommendations?: any[]
  metrics?: { label: string; value: string }[]
  backlinkData?: { metrics: any; backlinks: any[] } | null
  cwv?: { performanceScore: number; lcp?: any; inp?: any; cls?: any } | null
}

function ScoreBlock({ label, score, color }: { label: string; score: number; color: string }) {
  return (
    <View style={{ alignItems: 'center', width: 120, marginHorizontal: 16 }}>
      <View style={[styles.scoreCircle, { borderColor: color }]}>
        <Text style={[styles.scoreValue, { color }]}>{score}</Text>
      </View>
      <Text style={[styles.scoreLabel, { marginTop: 8 }]}>{label}</Text>
    </View>
  )
}

function MetricItem({ label, value, color }: { label: string; value: string; color?: string }) {
  return (
    <View style={styles.metricBox}>
      <Text style={styles.metricLabel}>{label}</Text>
      <Text style={[styles.metricValue, { color: color || colors.text }]}>{value}</Text>
    </View>
  )
}

function RecommendationCard({ rec, index }: { rec: any; index: number }) {
  const priority = (rec.priority || 'MEDIUM').toUpperCase()
  const domain = (rec.domain || 'SEO').toUpperCase()
  const priorityColor = priority === 'CRITICAL' ? colors.red : priority === 'HIGH' ? colors.yellow : colors.purple
  const domainColor = domain === 'AEO' ? colors.aeo : domain === 'GEO' ? colors.geo : colors.seo

  return (
    <View style={styles.card} wrap={false}>
      <View style={[styles.row, { marginBottom: 6 }]}>
        <Text style={[styles.badge, { backgroundColor: `${domainColor}20`, color: domainColor, marginRight: 6 }]}>{domain}</Text>
        <Text style={[styles.badge, { backgroundColor: `${priorityColor}20`, color: priorityColor }]}>{priority}</Text>
      </View>
      <Text style={[styles.h3, { marginBottom: 8 }]}>{index + 1}. {rec.title}</Text>

      {rec.description && (
        <View style={styles.whyBox}>
          <Text style={[styles.h4, { color: colors.muted, marginBottom: 4 }]}>Why This Matters</Text>
          <Text style={styles.body}>{rec.description}</Text>
        </View>
      )}

      <View style={styles.fixBox}>
        <Text style={[styles.h4, { color: colors.seo, marginBottom: 4 }]}>How To Fix</Text>
        {(rec.steps || [{ step: 1, title: 'Implementation', description: rec.description }]).map((step: any, i: number) => (
          <View key={i} style={{ marginBottom: 6 }}>
            <Text style={[styles.body, { fontWeight: 'bold', color: colors.text }]}>Step {step.step}: {step.title}</Text>
            <Text style={styles.body}>{step.description}</Text>
            {step.code && <Text style={styles.codeBlock}>{step.code}</Text>}
          </View>
        ))}
        {rec.code && !rec.steps?.some((s: any) => s.code) && (
          <Text style={styles.codeBlock}>{rec.code}</Text>
        )}
      </View>

      <View style={[styles.row, { marginTop: 4 }]}>
        {rec.estimatedTime && <Text style={[styles.small, { marginRight: 12 }]}>Time: {rec.estimatedTime}</Text>}
        {rec.platform && <Text style={[styles.small, { marginRight: 12 }]}>Platform: {rec.platform}</Text>}
        {rec.impactedScores && <Text style={[styles.small, { marginRight: 12 }]}>Impacts: {rec.impactedScores}</Text>}
      </View>
    </View>
  )
}

export function ProAuditReport({ url, date, scores, siteType, platform, overallFeedback, recommendations, metrics, backlinkData, cwv }: ProAuditReportProps) {
  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        <Text style={{ fontSize: 36, fontWeight: 'bold', color: colors.seo, marginBottom: 8 }}>Pro Audit Report</Text>
        <Text style={{ fontSize: 14, color: colors.text, marginBottom: 4 }}>{url}</Text>
        <Text style={{ fontSize: 10, color: colors.muted, marginBottom: 24 }}>{date}{siteType ? ` · ${siteType}` : ''}{platform ? ` · ${platform}` : ''}</Text>
        <View style={[styles.row, { marginBottom: 32, justifyContent: 'center' }]}>
          <ScoreBlock label="SEO Score" score={scores.seo} color={colors.seo} />
          <ScoreBlock label="AEO Score" score={scores.aeo} color={colors.aeo} />
          <ScoreBlock label="GEO Score" score={scores.geo} color={colors.geo} />
        </View>
        {overallFeedback && (
          <View style={[styles.card, { maxWidth: 400 }]}>
            <Text style={[styles.h4, { color: colors.seo, marginBottom: 4 }]}>Expert Verdict</Text>
            <Text style={styles.bodyLarge}>{overallFeedback}</Text>
          </View>
        )}
        <Text style={{ fontSize: 8, color: colors.muted, position: 'absolute', bottom: 30 }}>Generated by Duelly.ai · {date}</Text>
      </Page>

      {/* Metrics Page */}
      {metrics && metrics.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Key Metrics</Text>
          <View style={styles.divider} />
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {metrics.map((m, i) => (
              <View key={i} style={[styles.metricBox, { width: '30%', marginBottom: 6 }]}>
                <Text style={styles.metricLabel}>{m.label}</Text>
                <Text style={[styles.metricValue, { color: colors.text }]}>{m.value}</Text>
              </View>
            ))}
          </View>

          {/* CWV */}
          {cwv && cwv.performanceScore > 0 && (
            <View style={{ marginTop: 16 }}>
              <Text style={styles.h2}>Core Web Vitals</Text>
              <View style={styles.divider} />
              <View style={styles.row}>
                <Text style={[styles.h3, { color: colors.aeo }]}>Performance: {cwv.performanceScore}/100</Text>
              </View>
              <View style={[styles.row, { marginTop: 8 }]}>
                {cwv.lcp && <MetricItem label="LCP" value={cwv.lcp.displayValue} color={cwv.lcp.category === 'FAST' ? colors.green : cwv.lcp.category === 'SLOW' ? colors.red : colors.yellow} />}
                {cwv.inp && <MetricItem label="INP" value={cwv.inp.displayValue} color={cwv.inp.category === 'FAST' ? colors.green : cwv.inp.category === 'SLOW' ? colors.red : colors.yellow} />}
                {cwv.cls && <MetricItem label="CLS" value={cwv.cls.displayValue} color={cwv.cls.category === 'FAST' ? colors.green : cwv.cls.category === 'SLOW' ? colors.red : colors.yellow} />}
              </View>
            </View>
          )}

          {/* Backlinks */}
          {backlinkData && (
            <View style={{ marginTop: 16 }}>
              <Text style={styles.h2}>Link Building Intelligence</Text>
              <View style={styles.divider} />
              <View style={styles.row}>
                <MetricItem label="Domain Authority" value={`${backlinkData.metrics.domainAuthority}/100`} color={backlinkData.metrics.domainAuthority >= 40 ? colors.green : colors.yellow} />
                <MetricItem label="Linking Domains" value={backlinkData.metrics.linkingDomains.toLocaleString()} />
                <MetricItem label="Total Backlinks" value={backlinkData.metrics.totalBacklinks.toLocaleString()} />
                <MetricItem label="Spam Score" value={`${backlinkData.metrics.spamScore}%`} color={backlinkData.metrics.spamScore > 30 ? colors.red : colors.green} />
              </View>
              {backlinkData.backlinks.length > 0 && (
                <View style={{ marginTop: 8 }}>
                  <Text style={[styles.h4, { marginBottom: 4 }]}>Top Backlinks</Text>
                  {backlinkData.backlinks.slice(0, 10).map((bl: any, i: number) => (
                    <View key={i} style={[styles.row, { paddingVertical: 3, borderBottom: `1 solid ${colors.border}` }]}>
                      <Text style={[styles.small, { width: 20, fontWeight: 'bold', color: bl.domainAuthority >= 40 ? colors.green : colors.muted }]}>{bl.domainAuthority}</Text>
                      <Text style={[styles.small, { flex: 1 }]}>{bl.sourceDomain}</Text>
                      <Text style={[styles.small, { color: bl.isDofollow ? colors.green : colors.muted }]}>{bl.isDofollow ? 'follow' : 'nofollow'}</Text>
                    </View>
                  ))}
                </View>
              )}
            </View>
          )}
          <View style={styles.footer}><Text>Duelly.ai</Text><Text>{date}</Text></View>
        </Page>
      )}

      {/* Roadmap to 100 */}
      {recommendations && recommendations.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Roadmap to 100 - Prioritized Site Improvements</Text>
          <View style={styles.divider} />
          {recommendations.map((rec: any, i: number) => (
            <RecommendationCard key={i} rec={rec} index={i} />
          ))}
          <View style={styles.footer}><Text>Duelly.ai</Text><Text>{date}</Text></View>
        </Page>
      )}
    </Document>
  )
}
